# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://lijiaxuan.com
date_format: "ordinal"
title: 博客
author: 轩仔

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
paginate: 9
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/


lazy_load_disqus : false
